# Generated by Django 3.0.7 on 2020-07-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0002_auto_20200701_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='curr_theta',
            field=models.FloatField(default=0, verbose_name='the theta parameter of participant to the current stage'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='info_sum',
            field=models.FloatField(default=0, verbose_name='total information provided by tested trials'),
        ),
    ]
