# Generated by Django 3.0.7 on 2020-07-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0003_auto_20200701_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='finish_time',
            field=models.DateTimeField(null=True, verbose_name='time when exam is finished'),
        ),
    ]
