# Generated by Django 3.0.7 on 2020-07-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0004_auto_20200701_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num', models.IntegerField(default=20, verbose_name='the upper limit number of trials')),
                ('critical_r', models.FloatField(default=0.8, verbose_name='critical value to stop or continue')),
                ('is_on', models.BooleanField(default=False, verbose_name='whether the pattern is on')),
            ],
        ),
    ]
