# Generated by Django 3.0.7 on 2020-07-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0005_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='is_on',
            field=models.BooleanField(default=True, verbose_name='whether the pattern is on'),
        ),
    ]
