# Generated by Django 3.0.7 on 2020-07-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0006_auto_20200703_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='name',
            field=models.CharField(default='unnamedPattern', max_length=50),
        ),
    ]
